# ────────────── JWT Configuration ──────────────
app.jwt.secret=${JWT_SECRET:breakdownsecretkeybreakdownsecretkey12345}
app.jwt.expiration=${JWT_EXPIRATION:2592000000}  

# ────────────── AWS S3 Configuration ──────────────
aws.s3.region=${AWS_REGION:ap-south-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:breakdown-assistance}
aws.s3.access-key=${AWS_ACCESS_KEY:dummy}
aws.s3.secret-key=${AWS_SECRET_KEY:dummy}

# ────────────── Razorpay Configuration ──────────────
razorpay.key.id=${RAZORPAY_KEY_ID:dummy}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:dummy}

# ────────────── Mail Configuration ──────────────
spring.mail.username=${MAIL_USERNAME:yourmail@gmail.com}
spring.mail.password=${MAIL_PASSWORD:dummy}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# PostgreSQL external database (Render)
# PostgreSQL external database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7b3it2a214c73ckagpg-a.oregon-postgres.render.com:5432/breakdowndb
spring.datasource.username=breakdownuser
spring.datasource.password=XoqpFteo5CUAXUhzBRsUB2uJDMPKJAGO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
